# Generated by Django 2.0.1 on 2018-03-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timus_id', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('solved', models.IntegerField(default=0)),
                ('solved_today', models.IntegerField(default=0)),
                ('current_phase', models.DateField(auto_now=True)),
            ],
        ),
    ]
